"""Collect standalone GLSL presets into a browser-ready static module (stdlib only)."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read_preset(path):
    text = path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    metadata = {}
    lines = text.splitlines(keepends=True)
    offset = 0
    for line in lines:
        match = re.fullmatch(r"//\s*@([a-z]+)\s+(.+?)\s*", line)
        if not match:
            break
        key, value = match.groups()
        if key not in {"name", "category", "generator", "order", "default"}:
            raise ValueError(f"{path.name}: unknown metadata @{key}")
        if key in metadata:
            raise ValueError(f"{path.name}: duplicate @{key}")
        metadata[key] = value
        offset += len(line)
    for key in ("name", "category", "generator"):
        if key not in metadata:
            raise ValueError(f"{path.name}: missing @{key}")
    if metadata["generator"] not in {"true", "false"}:
        raise ValueError(f"{path.name}: @generator must be true or false")
    default = metadata.get("default")
    if default not in {None, "filter", "generator"}:
        raise ValueError(f"{path.name}: @default must be filter or generator")
    generator = metadata["generator"] == "true"
    if default and generator != (default == "generator"):
        raise ValueError(f"{path.name}: @default conflicts with @generator")
    code = text[offset:]
    if code.startswith("\n"):
        code = code[1:]
    if not code.strip():
        raise ValueError(f"{path.name}: shader body is empty")
    try:
        order = int(metadata.get("order", "1000"))
    except ValueError:
        raise ValueError(f"{path.name}: @order must be an integer") from None
    return order, default, dict(name=metadata["name"], category=metadata["category"],
                                generator=generator, code=code)


def generate(source_dir, output):
    entries = [(read_preset(path), path.name) for path in source_dir.glob("*.glsl")]
    entries.sort(key=lambda entry: (entry[0][0], entry[1]))
    presets, defaults, names = [], {}, set()
    for (_, default, preset), filename in entries:
        if preset["name"] in names:
            raise ValueError(f"{filename}: duplicate preset name {preset['name']!r}")
        names.add(preset["name"])
        if default:
            if default in defaults:
                raise ValueError(f"{filename}: duplicate @default {default}")
            defaults[default] = len(presets)
        presets.append(preset)
    if set(defaults) != {"filter", "generator"}:
        raise ValueError("Exactly one @default filter and one @default generator are required")
    content = "// Generated by scripts/generate_glsl_presets.py. Edit glsl-presets/*.glsl instead.\n"
    content += "export const GLSL_PRESETS = " + json.dumps(presets, ensure_ascii=False, indent=2) + ";\n"
    for kind in ("filter", "generator"):
        content += f"export const DEFAULT_{kind.upper()}_CODE = GLSL_PRESETS[{defaults[kind]}].code;\n"
    # Validate everything before touching the last usable output; avoid unnecessary rewrites.
    if not output.exists() or output.read_text(encoding="utf-8") != content:
        output.write_text(content, encoding="utf-8", newline="\n")
    return len(presets)


if __name__ == "__main__":
    try:
        count = generate(ROOT / "glsl-presets", ROOT / "glsl-presets.generated.js")
    except (ValueError, OSError) as error:
        raise SystemExit(f"GLSL preset generation failed: {error}")
    print(f"GLSL presets: {count}")
